name: Release Version

on:
  push:
    branches:
      - main # Runs only when merging to main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions: # ✅ ADD THIS
      contents: write # Required to push commits/tags

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Ensure using Node.js 20+

      - name: Install dependencies
        run: npm install --save-dev semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/npm conventional-changelog-conventionalcommits

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ensure GitHub token is used
        run: npx semantic-release

        # 🚀 Run this AFTER semantic release generates the tag
      - name: Get latest tag
        id: get_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Create branch from tag
        run: |
          git checkout -b branch-from-${{ steps.get_tag.outputs.tag }} ${{ steps.get_tag.outputs.tag }}
          git push origin branch-from-${{ steps.get_tag.outputs.tag }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: branch-from-${{ steps.get_tag.outputs.tag }}
          base: pre-dev  # Target branch for PR
          title: "PR for release ${{ steps.get_tag.outputs.tag }}"
          body: "This PR contains changes from tag ${{ steps.get_tag.outputs.tag }}."
